USE [master]
GO


ALTER DATABASE [Catalog] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Catalog].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Catalog] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Catalog] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Catalog] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Catalog] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Catalog] SET ARITHABORT OFF 
GO

ALTER DATABASE [Catalog] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Catalog] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Catalog] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Catalog] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Catalog] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Catalog] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Catalog] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Catalog] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Catalog] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Catalog] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Catalog] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Catalog] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Catalog] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Catalog] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Catalog] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Catalog] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Catalog] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Catalog] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Catalog] SET  READ_WRITE 
GO

ALTER DATABASE [Catalog] SET RECOVERY FULL 
GO

ALTER DATABASE [Catalog] SET  MULTI_USER 
GO

ALTER DATABASE [Catalog] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Catalog] SET DB_CHAINING OFF 
GO


USE [Catalog]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NULL,
	[Description] [nvarchar](50) NULL,
	[IsEnable] [bit] NULL,
	[LastUpdate] [datetime] NULL,
	[Prices] [money] NULL,
 CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Product] ON
INSERT [dbo].[Product] ([Id], [Name], [Description], [IsEnable], [LastUpdate], [Prices]) VALUES (1, N'Name236903c6-b8e4-4129-80d5-759c89665abb', NULL, 1, CAST(0x0000A6BB00DAD900 AS DateTime), 123.0000)
SET IDENTITY_INSERT [dbo].[Product] OFF
